Php8 and symfony5
MovingImage24/MiRestExtraBundle pull request #3
Opened 2021-06-14 13:56 UTC by GoranDimitrovski

2021-06-22 17:39 UTC, kudrmudr approved these changes

2021-06-24 14:52 UTC, pavbis requested changes

2021-06-24 14:52 UTC, pavbis commented on tests/EventListener/SecurityListenerTest.php
> +        $requestType = HttpKernelInterface::MAIN_REQUEST;
Where this constant comes from?
I can't find it in Symfony's interface
https://github.com/symfony/http-kernel/blob/5.2/HttpKernelInterface.php

2021-06-24 14:52 UTC, pavbis commented on composer.json
> +    "phpspec/prophecy-phpunit": "^2.0",
I would rather remove all prophecy calls in the tests and use native mocking stuff from phpunit as installing another dep to bring that "tests" running. There is a reason I guess why phpunit decided to remove prophecy.

2021-06-24 15:03 UTC, GoranDimitrovski commented on composer.json
> +    "phpspec/prophecy-phpunit": "^2.0",
its from the version 5.3 https://github.com/symfony/http-kernel/blob/5.3/HttpKernelInterface.php

2021-06-24 15:03 UTC, GoranDimitrovski commented on tests/EventListener/SecurityListenerTest.php
> +        $requestType = HttpKernelInterface::MAIN_REQUEST;
its from the version 5.3 https://github.com/symfony/http-kernel/blob/5.3/HttpKernelInterface.php

2021-06-24 15:05 UTC, GoranDimitrovski commented on composer.json
> +    "phpspec/prophecy-phpunit": "^2.0",
Maybe we can do this in a follow up ticket

2021-06-24 17:23 UTC, kudrmudr commented on tests/EventListener/SecurityListenerTest.php
> +        $requestType = HttpKernelInterface::MAIN_REQUEST;
but in require-dev you have symfony 5.2

2021-06-24 18:37 UTC, GoranDimitrovski commented on tests/EventListener/SecurityListenerTest.php
> +        $requestType = HttpKernelInterface::MAIN_REQUEST;
@kudrmudr That is true but even if the required dev packages are set to 5.2
"symfony/framework-bundle": "5.2",
"symfony/validator": "5.2"
Their required packages are not required with a specific version. So thats how we end up at the end with symfony/http-kernel with version 5.3

2021-06-29 08:28 UTC, pavbis approved these changes

2021-06-29 13:58 UTC, merged